#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["tiktoken>=0.7.0"]
# ///
"""Write token counts of AGENTS.md, .agents/rules and .agents/skills to .agents/cost.md."""

from dataclasses import dataclass
from pathlib import Path

import tiktoken

ENCODING = "o200k_base"
CATEGORIES = ("Core", "Rules", "Skills")


@dataclass(frozen=True)
class FileTokens:
    rel_path: str
    category: str
    tokens: int


def find_files(repo_root: Path) -> list[tuple[str, Path]]:
    """Return (category, path) pairs for all tracked agent files."""
    agents_dir = repo_root / ".agents"
    return [
        *[("Core", path) for path in [repo_root / "AGENTS.md"] if path.is_file()],
        *[("Rules", path) for path in sorted((agents_dir / "rules").glob("*.md"))],
        *[("Skills", path) for path in sorted((agents_dir / "skills").rglob("*.md"))],
    ]


def count_tokens(files: list[tuple[str, Path]], repo_root: Path) -> list[FileTokens]:
    """Count tokens per file."""
    encoder = tiktoken.get_encoding(ENCODING)
    return [
        FileTokens(
            rel_path=path.relative_to(repo_root).as_posix(),
            category=category,
            tokens=len(encoder.encode(path.read_text(encoding="utf-8"))),
        )
        for category, path in files
    ]


def render_markdown(file_tokens: list[FileTokens]) -> str:
    """Render summary and per-file details as markdown."""
    by_category = {
        category: sum(item.tokens for item in file_tokens if item.category == category)
        for category in CATEGORIES
    }
    summary_rows = [f"| {category} | {tokens:,} |" for category, tokens in by_category.items()]
    detail_rows = [
        f"| `{item.rel_path}` | {item.category} | {item.tokens:,} |"
        for item in sorted(file_tokens, key=lambda item: item.tokens, reverse=True)
    ]
    return "\n".join(
        [
            "<!-- Auto-generated by scripts/calculate_agent_cost.py, do not edit -->",
            f"# Agent token usage ({ENCODING})",
            "",
            "| Scope | Tokens |",
            "| --- | ---: |",
            f"| **Total** | **{sum(by_category.values()):,}** |",
            *summary_rows,
            "",
            "## Details per file",
            "",
            "| File | Category | Tokens |",
            "| --- | --- | ---: |",
            *detail_rows,
            "",
        ]
    )


def main() -> None:
    repo_root = Path(__file__).resolve().parent.parent
    file_tokens = count_tokens(find_files(repo_root), repo_root)
    (repo_root / ".agents" / "cost.md").write_text(render_markdown(file_tokens), encoding="utf-8")


if __name__ == "__main__":
    main()
